{{- if .Values.acrCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: acrkublogin
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}