{{- if .Values.acrCredentials.enabled }}
{{- if not (lookup "v1" "Secret" .Release.Namespace "acrKubLogin") }}
apiVersion: v1
kind: Secret
metadata:
  name: acrKubLogin
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}