apiVersion: v1
kind: Service
metadata:
  name: {{ include "modern-app.fullname" . }}
  labels:
    {{- include "modern-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
  selector:
    {{- include "modern-app.selectorLabels" . | nindent 4 }}